name: Excercise Companion
title: Excercise Companion

remote_theme: just-the-docs/just-the-docs
search_enabled: false

nav_external_links:
  - title: App Repo on Github
    url: https://github.com/ExerciseCompanion/app/tree/main
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
